language: java
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - cd app/
  - echo "Let's start maven package!"
  - cd ..
  - echo "docker folder!"
script:
  - docker-compose build
before_deploy:
  echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag docker-to-aws-with-java:latest dansanti2019/docker-to-aws-with-java:latest;
    docker push dansanti2019/docker-to-aws-with-java:latest;
  on:
    branch: master
    
notifications:
  email: false